//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WearShopX.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> size { get; set; }
        public string category { get; set; }
    }
}
